services:
  - type: web
    name: gemini-api-proxy
    env: python
    plan: free
    region: oregon  # 美国西海岸，对中国访问友好
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: python run_server.py
    healthCheckPath: /health
    autoDeploy: true
    
    # 环境变量
    envVars:
      - key: PORT
        generateValue: true
      - key: PYTHONPATH
        value: .
      - key: RENDER_EXTERNAL_URL
        generateValue: true
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
    
    # 自定义域名配置（可选）
    # customDomains:
    #   - name: your-domain.com
    #     certificateId: your-cert-id

# 数据库配置（如果需要PostgreSQL）
# databases:
#   - name: gemini-proxy-db
#     databaseName: gemini_proxy
#     user: gemini_user
#     plan: free

# 定时任务配置（如果需要）
# cronJobs:
#   - name: cleanup-logs
#     schedule: "0 2 * * *"  # 每天凌晨2点
#     command: python -c "from database import Database; db = Database(); db.cleanup_old_logs()"